import type { Metadata } from "next";
import "./globals.css";
import '../sf-pro.css' // Import your sf-pro.css file
import TopHeader from "../components/TopHeader/TopHeader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <TopHeader/>
        {children}
      </body>
    </html>
  );
}
